### ISSUE TITLE
Example workflow error

### ISSUE THREAD

**Issue by Arjay7891** [wri/retrieveR#4]
Trying to recreate the example workflow I'm getting the following error:

> corpus <- prep_documents("pdfs")
Splitting pdf files 
  |============================| 100%
Running OCR on the corpus 
  |============================| 100%

Data loaded 
Error in `$<-.data.frame`(`*tmp*`, "sentences", value = NA_character_) : 
  replacement has 1 row, data has 0

[this fix](https://stackoverflow.com/questions/28614199/r-error-in-data-frame-replacement-has-items-need) could help:

**Comment by JohnMBrandt** [comment]
Hey - thanks for adding the issue to the repo. 
What is happening is that the OCR is finishing and the next stage - creating the corpus from the individual txt files - is failing. 

What operating system and version of R are you using? (3.5.1+ and x386 preferred on WRI laptops).

Sometimes I have noticed that on Windows this fails due to length requirements for files. File paths on Windows are not allowed to be over 250 characters. Depending on your working directory and the length of the names of your PDFS, the file and folder creation may fail. I have debugged this on Mac OSX 10.13.4, Windows 10, and Ubuntu 16.04 with R 3.5.1 and have confirmed that it works on all systems without a hitch - so I'm expecting that it's an issue with path limits.

To see where the error is coming from, could you try running the parts of prep_documents separately?

Starting with

`run_ocr("pdfs")`

This should create, within the pdfs folder, separate folders indexed by the document with individual page numbers saved as separate .txt files.

If this does not work, could you try this:

`rtika::tika_jar()` to see whether or not the underlying Java packages are being properly loaded?

Let me know if both of these work fine. If they do, you can try the next step in the `prep_documents` pipeline:

`corpus <- create_corpus("pdfs")`

If at any point you get an error, could you please immediately run

`traceback()` and paste the results? That would help me understand which helper function within the functions are throwing the error.

**Comment by Arjay7891** [comment]
I had installed the package with the RGui for 32 bit and then switched to RStudio for scripting and didn't realize my RStudio was still set to the 64 bit version, so that was the problem. Now it works. Thanks!
